services:
  - type: web
    name: resume-analyzer
    env: python
    plan: free
    buildCommand: "./render-build.sh"
    startCommand: "./render-start.sh"
    envVars:
      - key: RENDER
        value: "true"
      - key: PYTHON_VERSION
        value: "3.11.0"
    healthCheckPath: /health
